name: yarn-install
description: 'This action installs dependencies using yarn'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Get yarn cache directory
      id: yarn-cache
      run: |
        echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-

    - name: yarn install
      run: |
        yarn
      shell: bash
