version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - yarn_cache:/workspace/node_modules
    command: sleep infinity

volumes:
  yarn_cache:
