name: build-on-pull

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/yarn-install
        id: yarn-install

      - name: yarn test
        run: |
          yarn test

      - name: yarn build
        run: |
          yarn build
