name: lighthouse-on-pull

on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse-on-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/yarn-install
        id: yarn-install

      - name: yarn lighthouse
        run: |
          yarn lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
